version: "3.7"

services:
  app:
    build: .
    volumes:
      - ./public:/app/public
      - ./lib:/app/lib
      - ./test:/app/test
      - ./settings.js:/app/settings.js
      - ./package.json:/app/package.json
      - node_modules:/app/node_modules
    environment:
      - db_host=db
      - db_password=supersecret
      - db_user=thumbs_up
      - githubUrl=
      - client_id=
      - client_secret=
      - state_password=
    entrypoint: ["/wait_for_postgres.sh"]
    ports:
      - 5000:5000

  db:
    build:
      context: ./postgres
    environment:
      - POSTGRESQL_USERNAME=thumbs_up
      - POSTGRESQL_PASSWORD=supersecret
      - POSTGRESQL_DATABASE=thumbs_up
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - docker-entrypoint-preinitdb.d:/docker-entrypoint-preinitdb.d
      - postgres-data:/bitnami/postgresql
    ports:
      - 5432:5432

volumes:
  node_modules:
  docker-entrypoint-preinitdb.d:
  postgres-data:
