version: "3.7"

services:
  app:
    image: node:latest
    volumes:
      - ./lib:/app/lib
      - ./test:/app/test
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./settings.js:/app/settings.js
      - ./wait_for_postgres.sh:/wait_for_postgres.sh
      - node_modules:/app/node_modules
    environment:
      - db_host=db
      - db_password=supersecret
      - db_user=thumbs_up
    working_dir: /app
    entrypoint: ["/wait_for_postgres.sh", "db"]
    command: ["npm", "start"]
    ports:
      - 5000:5000

  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=thumbs_up
      - POSTGRESQL_PASSWORD=supersecret
      - POSTGRESQL_DATABASE=thumbs_up
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - docker-entrypoint-preinitdb.d:/docker-entrypoint-preinitdb.d
      - postgres-data:/bitnami/postgresql
    ports:
      - 5432:5432

volumes:
    node_modules:
    docker-entrypoint-preinitdb.d:
    postgres-data:
